### ISSUE TITLE
Normalizacja bazy danych.

### ISSUE THREAD

**Issue by SlimaKCoder** [Dzikoysk/FunnyGuilds#129]
Powinniście znormalizować bazę danych. Chodzi o to, że w tabeli 'guilds' w kolumnie 'members' są wypisani wszyscy gracze należący do danej gildii. Pobranie informacji do jakiej gildii należy dany gracz jest strasznie kłopotliwe, ta informacja powinna być w tabeli 'users' lub w zupełnie nowej tabeli.

**Comment by dzikoysk** [comment]
#1074
