### ISSUE TITLE
Problemy z 3.5!

### ISSUE THREAD

**Issue by Szeder32** [Dzikoysk/FunnyGuilds#205]
Nie można postawić tabliczki.
Punkty nad głowami są, ale punktów jest 0.

A i PS: nie można się logować ;/ Usunęłem plugin do 1. i postawienie tabliczki działa.

**Comment by Dzikoysk** [comment]
1. To nie wina FunnyGuilds
2. Dziwne... Podaj pluginy

**Comment by Szeder32** [comment]
@EDITowałem post.

**Comment by Soanger** [comment]
Pierwsze to wina funnyguilds każdy ma ten problem.

**Comment by TheMolkaPL** [comment]
#208

**Comment by Dzikoysk** [comment]
Generalnie te tabliczki są conajmniej dziwne, szczególnie, że nic co mogłoby być ewentualnie z tym związane nie było zmieniane.

Podajcie mi swoje pluginy od logowania
