### ISSUE TITLE
Piszę własny plugin na formatowanie chatu. 

### ISSUE THREAD

**Issue by KifKick** [Dzikoysk/FunnyGuilds#206]
Jak uzyskać TAG i liczbę punktów?

**Comment by TheMolkaPL** [comment]
`{TAG}` - tag gildii
`{POINTS}` - punkty

**Comment by Dzikoysk** [comment]
Ew. masz jeszcze {RANK}, może się przyda :)

**Comment by KifKick** [comment]
Ale że kod java, nie chodziło mi o ustawienie w ESS. :P

**Comment by Dzikoysk** [comment]
Jak dodasz w setFortmat() te tagi też będzie działać :)
