### ISSUE TITLE
gildia chat

### ISSUE THREAD

**Issue by michaa202** [Dzikoysk/FunnyGuilds#207]
co trzeba zrobić by na normalnym chacie pisało tag gildi by pisało np [gildia] ranga gracz -> wiadomość 
robiłem to w essentials chat i usunełem # i tak niedziała :(

**Comment by TheMolkaPL** [comment]
Musisz użyć pluginu do formatowania chatu. Przykładowo [EssentialsChat](http://dev.bukkit.org/bukkit-plugins/essentials/) lub [GroupManager](http://wiki.ess3.net/wiki/Group_Manager).
