### ISSUE TITLE
bug z rankingiem nad głową gracza

### ISSUE THREAD

**Issue by zorro8003PL** [Dzikoysk/FunnyGuilds#208]
Ja mam 1000 pkt, a nad głową pisze że mam 0 pkt
(Mam wersje 3.5.1 NewYear)

**Comment by TheMolkaPL** [comment]
Może log z konsoli? Kopia config.yml (na [Pastebin](http://pastebin.com))?

**Comment by zorro8003PL** [comment]
W konsoli nie ma błędów żadnych, a w configu nic nie grzebałem, mam taki jaki plugin wygenerował

**Comment by Dzikoysk** [comment]
Przydadzą się pluginy, jakie masz na serwerze. Generalnie, skoro masz 0, to znaczy, że plugin teoretycznie ustawia to dummy, ale nie aktualizuje wszystkich graczy. Powiedz, kiedy dany bug występuje?

**Comment by zorro8003PL** [comment]
Plugins (15): AutoSaveWorld, NoCheatPlus, WorldEdit, MaxBans, Skript, Essentials, WildSkript, EssentialsChat, ClearLag, PermissionsEx, LagMeter, FunnyGuilds, EssentialsSpawn, Multiverse-Core, WorldGuard

**Comment by Dzikoysk** [comment]
"Powiedz, kiedy dany bug występuje?"

**Comment by zorro8003PL** [comment]
Jak wchodzę na serwer

**Comment by Soanger** [comment]
W różnym czasie, zazwyczaj po relogu.

**Comment by Meehoweq** [comment]
Tak nagle. Wszystko jest ok i nagle z ilustam pkt robi sie 0.

**Comment by kukubaczek** [comment]
siema

**Comment by ZkfMaster** [comment]
mam dokładnie ten sam problem
