### ISSUE TITLE
Kiedy będzie funkcja AntyLogout?

### ISSUE THREAD

**Issue by TheAzaveR** [Dzikoysk/FunnyGuilds#217]
Czekam na niego gorąco! xD

**Comment by Dzikoysk** [comment]
Postaram się o to w 4.0 :)

Na razie masa roboty, jak znajdę chwilę, to się za to wszystko wezmę. Odświeżymy plugin itd., głównie poprawki, bo robiłem ostatnio dużo rzeczy na szybko ze względu na ograniczoną liczbę czasu i troszkę błędów się nazbierało. Nie chce mi się nawet tego przeglądać xd Powiem tyle, że fg ma teraz ciężki okres, ale niedługo sytuacja wróci do normy. Musicie mi wybaczyć :sob:
