### ISSUE TITLE
Topka gildii od danej ilości graczy

### ISSUE THREAD

**Issue by CzlowiekKuktas** [Dzikoysk/FunnyGuilds#219]
Możesz wprowadzić to, żeby gildia, która ma np. 1/2/3 osoby nie mogła być w rankingu? Tylko np. topka od 5 osób w gildii.

**Comment by Soanger** [comment]
Jestem za, albo przynajmniej dwie osoby, jak jest tylko założyciel w gildii i ma 1000 ranku jest w topce :P

**Comment by CzlowiekKuktas** [comment]
Dwie osoby to za mało. ;)
