### ISSUE TITLE
Propozycja

### ISSUE THREAD

**Issue by Reydann** [Dzikoysk/FunnyGuilds#223]
Witam, proponuję w następnej aktualizacji aby dodać możliwość czy komenda ma być wykonywana przykładowo z:
"/zaloz" lub z "/g zaloz"

**Comment by zorro8003PL** [comment]
To wchodzisz w config szukasz komendy zaloz i zamiast zaloz wpisujesz gildia zaloz a w aliases wpisujesz g zaloz
czyli tak:
commands:
  create:
    name: 'gildia zaloz'
    aliases:
    - 'g zaloz'

**Comment by Reydann** [comment]
Nie jestem idiotą, to nie działa. Chyba, że w name ale podczas użycia na serwerze komendy "/g" wywala błędy.
