### ISSUE TITLE
odnawianie gildii

### ISSUE THREAD

**Issue by zorro8003PL** [Dzikoysk/FunnyGuilds#231]
Dwa bugi:
1. Jak mam validity-when: 0 to i tak musze czekać jakiś czas na przedłużenie ważności gildii.
2. Dalej nie działa te czekanie na przedłużenie gildii, bo jak wpisuje /przedluz to pisze że moge przedłuzyć gildie dopiero wtedy, kiedy ona wygasa...

**Comment by Dzikoysk** [comment]
1. Oki
2. Bo masz validity-when: 0

**Comment by zorro8003PL** [comment]
2.
# Ile dni przed koncem wygasania mozna przedluzyc gildie (wpisz 0, jezeli funkcja ma byc wylaczona)
validity-when: 0
ale ja napisałem 0 po to żeby to nie działało te czekanie na przedłużenie gildii, a i tak trzeba czekać

**Comment by Dzikoysk** [comment]
No ok, ale 2 problem jest jest spowodowany tym ustawieniem :)

Jutro w końcu update :)
