### ISSUE TITLE
#7.01.2014 - 3.9 Cleaned

### ISSUE THREAD

**Issue by Dzikoysk** [Dzikoysk/FunnyGuilds#232]
@"Informacja o aktualizacji"

**Comment by zorro8003PL** [comment]
O której godzinie mniej więcej będzie?

**Comment by TheMolkaPL** [comment]
> O której godzinie mniej więcej będzie?

Co Ty taki niedoczekany? :sweat_smile: 
Będzie jak będzie

**Comment by kepo70** [comment]
Bacznie czekamy ;)

**Comment by Dzikoysk** [comment]
https://github.com/Dzikoysk/FunnyGuilds/releases/tag/3.9

**Comment by NorthPL** [comment]
Ta wersja będzie działać z Spigotem 1.8? Bo poprzednia wywalała błędy z prędkością światła... :package:

**Comment by Dzikoysk** [comment]
Jedynie z tym spigotem pod 1.7.x - 1.8
