### ISSUE TITLE
wywala z serwera

### ISSUE THREAD

**Issue by zorro8003PL** [Dzikoysk/FunnyGuilds#235]
Jak się uderza w ender crystal to wywala z serwera
(Wersja 3.9 Cleaned)

**Comment by TheMolkaPL** [comment]
Log z konsoli?

**Comment by zorro8003PL** [comment]
Nie ma żadnych błędów, tylko jak mnie wywala to pisze w konsoli:
[22:20:03] [Server thread/INFO]: zorro8003PL lost connection: Internal Exception: java.lang.IllegalStateException: PacketSendEvent cannot be triggered asynchronously from inside synchronized code.

**Comment by TheMolkaPL** [comment]
Bug w kodzie dla @Dzikoysk ;)

**Comment by Dzikoysk** [comment]
Ale to by oznaczało, że ChannelHandler działa asynchronicznie a to mocno komplikuje sprawę. Wywoływać tak często Runnable... Hmm.

**Comment by zorro8003PL** [comment]
Dzikoysk, jeszcze znowu źle działa to przedłużanie gildii, bo mam vadility-when: 5d a i tak pisze że moge przedłużyć gildie w dniu wygaśnięcia

**Comment by Dzikoysk** [comment]
Patrzyłem na to kilka razy, w kodzie jest wszystko dobrze

**Comment by zorro8003PL** [comment]
patrz http://scr.hu/19xy/8owsi

**Comment by Dzikoysk** [comment]
Sprawdź 2 build - jest pod poprzednim linkiem

**Comment by zorro8003PL** [comment]
Tak samo, xd I też wywala z serwera po kliknięciu w ender crystal :o

**Comment by Dzikoysk** [comment]
Dobra, na dziś mam dość. Jutro okolo 9/10 nad tym usiądę. Ew. @TheMolkaPL możesz się tym pobawić xd
