### ISSUE TITLE
2 bugi

### ISSUE THREAD

**Issue by zorro8003PL** [Dzikoysk/FunnyGuilds#237]
1. Jak się uderza w ender crystal to się nic nie dzieje :o 
2. Jak endercrystala nie ma to jak się respi to respi się na najwyższym bloku gildii, a nie na poziomie Y, wyznaczonym w configu

**Comment by Dzikoysk** [comment]
Tepnij się do gildii i sprawdź gdzie się znalazłeś. (Tylko bądź w powietrzu przed teleportacją)

**Comment by zorro8003PL** [comment]
2. jak się tepnąłem do gildii (w powietrzu) to znalazłem się na Y: 120, a w configu mam ustawiony poziom ender crystala na Y: 60
1. Lewym i prawym klikałem i się nic nie działo

**Comment by Dzikoysk** [comment]
1. Czyli działa... Bo pod prawym jest info, a lewym się atakuje - kryształ należy do Ciebie, to nie możesz mu nic zrobić.
2. Ta gildia mogła być założona, gdy nie było tego limitu. Środek został w starym miejscu, więc tam go spawnuje... Teoretycznie. Spróbuj przy nowej gildii.

**Comment by zorro8003PL** [comment]
A no, działa.
Tylko jak się usuwa gildie to nie znika ender crystal, i jak się uderza w ten ender crystal to pisze że musze być w gildii żeby inną zaatakować.
