### ISSUE TITLE
punkty nad głową

### ISSUE THREAD

**Issue by zorro8003PL** [Dzikoysk/FunnyGuilds#240]
Jeszcze czasami (ale rzadko) bugują się punkty nad głową gracza i pokazuje 0 pkt
-> http://scr.hu/19xy/m7iz0

**Comment by TheMolkaPL** [comment]
STEVE XDDD BRUDAS

**Comment by Mroczny337** [comment]
Ciągle piszesz jakieś bugi zrób to w jednym issue ;d
