### ISSUE TITLE
/ga endercrystal

### ISSUE THREAD

**Issue by zorro8003PL** [Dzikoysk/FunnyGuilds#241]
może dodaj komende /ga endercrystal <tag gildii>, która usuwa endercrystal danej gildii i respi go od nowa

**Comment by Dzikoysk** [comment]
Emmm, po co?

**Comment by zorro8003PL** [comment]
jakby się ender crystal zbugował lub coś

**Comment by TheMolkaPL** [comment]
Jak się zbuguje to pisz issue.

**Comment by Dzikoysk** [comment]
To jest wysyłane packetami. Nieważne co by się stało, po relogu i tak wraca to do punktu wyjścia :)

**Comment by zorro8003PL** [comment]
a ok

**Comment by sokrates1231** [comment]
Dlatego przez to się buguje /ga przenies :), dopiero po resecie im przenosi gildię . To samo z usuwaniem gildii .
