### ISSUE TITLE
Niedziałająca opcja w configu

### ISSUE THREAD

**Issue by CzlowiekKuktas** [Dzikoysk/FunnyGuilds#242]
Kolejna chyba nie działająca opcja w configu dotycząca tablisty;
 Ping wyswietlany na tab
player-list-ping: 0

Dałoby się zrobić tak, żeby to:
http://scr.hu/1gy8/s814g
zamienić na to: http://scr.hu/1gy8/4mq4f?

**Comment by TheMolkaPL** [comment]
To pierwsze lepiej wygląda :cactus:

**Comment by CzlowiekKuktas** [comment]
Moim zdaniem o wiele gorzej, ale to nie o tym mowa w tym temacie. :cactus:
