### ISSUE TITLE
Nowa wersja

### ISSUE THREAD

**Issue by CzlowiekKuktas** [Dzikoysk/FunnyGuilds#250]
Wbijam na serwer z nową wersją i wyskakuje "Nick zawiera nieprawidłowe znaki"

**Comment by TheMolkaPL** [comment]
Nicki muszą zawierać znaki z oraz pomiędzy `A - Z`, `a - z`, `0 - 9` może także posiadać znak podłogi `_`.

**Comment by CzlowiekKuktas** [comment]
Na poprzedniej wersji mogę wbić bez problemu.

**Comment by TheMolkaPL** [comment]
Jaki masz nick? Inne nicki niż podałem wyżej nie są wspomagane przez klienta, serwer ani pluginy.

**Comment by CzlowiekKuktas** [comment]
Chwila, spróbuję wgrać jeszcze raz.

**Comment by CzlowiekKuktas** [comment]
Nie działa, na poprzedniej wersji nie było żadnego problemu.

**Comment by Dzikoysk** [comment]
Podaj nick

**Comment by CzlowiekKuktas** [comment]
HymasterPL

**Comment by Dzikoysk** [comment]
Ok, już widzę, mój błąd. Za hmmm... ~godzinę dam update

**Comment by CzlowiekKuktas** [comment]
"Same poprawki"? :cactus:
