### ISSUE TITLE
Parę propozycji

### ISSUE THREAD

**Issue by ZkfMaster** [Dzikoysk/FunnyGuilds#255]
Mógłbyś w przyszłych aktualizacjach zrobić, że gdy gracz wyloguje się podczas walki do zalicza mu śmierć a temu co go atakował zabicie?? Poza tym gdy gracz zginie bądź zostanie zabity przez jakiegoś  moba to zalicza mu śmierć ale nie pomniejsza rankingu?

**Comment by TheMolkaPL** [comment]
W końcu to serwery PvP (Player vs Player) czy PvE (Player vs Entity)?
