### ISSUE TITLE
Propozycje.

### ISSUE THREAD

**Issue by sokrates1231** [Dzikoysk/FunnyGuilds#256]
1. Komenda /ga chat - Dla administracji ( adminów,modów,helperów ) - Np. Może ktos na chat gildyjnym reklamować a administracja tego nie widzi .

2. Komeda /limit - zwiększanie limitu członków w gildii , z 15 na 16 członków np. za ustaloną kwotę.

3. [Ranking gildii] Jeśli jest w niej tylko założyciel(1osoba) żeby tej gildi nie było w topce .

**Comment by TheMolkaPL** [comment]
1. Może lepiej `/ga spy`?
3. Możesz wytłumaczyć, który "1 gracz"?

**Comment by Esa123** [comment]
jesli jedna osoba jest w gildii to jest w topce.. beznadzieja

**Comment by TheMolkaPL** [comment]
Rasizm.

**Comment by sokrates1231** [comment]
/ga spy też może być kto jak woli XD .
3. Poprawione.

**Comment by Soanger** [comment]
Jestem za 3 i 2

**Comment by sokrates1231** [comment]
@Soanger 
A 1 ? Chyba byś reklamy nie chciał na serwie ?:D

**Comment by TheMolkaPL** [comment]
@sokrates1231 Ale jeżeli pisze na gildyjnym no to pisze do swoich znajomych z gildii, nie do randomów na serwerze. To jest jak prywatna wiadomość, a więc ciężko to nazwać reklamą.

**Comment by xW0LFx** [comment]
Ja popieram sokratesa mozna reklamowac na !!! chat globalny gildii ;p
