### ISSUE TITLE
Propozycja

### ISSUE THREAD

**Issue by Bodzioo9** [Dzikoysk/FunnyGuilds#260]
Gdzieś już widziałem, że ktoś to napisał, ale prosił bym żeby w nowym update zrobić, aby gildyjna topka zaliczała się od pięciu (5) osób w gildii ;).

**Comment by TheMolkaPL** [comment]
Zanim zrobisz nowy issue rusz głową i użyj WYSZUKIWARKI -.- :hankey:  #259
