### ISSUE TITLE
Propozycja

### ISSUE THREAD

**Issue by Bodzioo9** [Dzikoysk/FunnyGuilds#264]
Dodać, że kiedy gracz tworzy gildie to w configu można ustawić, że ender crystal ma się stowrzyć 10 kratek pod graczem bo jeśli gracz założy na 200 poziomie i sobie ustawie 60 to, nie ma różnicy, czy założy na 100 poziomie, czy 200. (Sory za takie masło maślane....)

**Comment by Dzikoysk** [comment]
Ustaw 0 w cfg, to się będzie pojawiał tam gdzie on sobie wybierze

**Comment by Bodzioo9** [comment]
No właśnie ale chodzi mi o to, że ma to być 10 kratek pod graczem zawsze
W każdym przypadku

**Comment by Dzikoysk** [comment]
Bez sensu xd
