### ISSUE TITLE
dodanie zmiennych do chatu

### ISSUE THREAD

**Issue by SkymaxPlay** [Dzikoysk/FunnyGuilds#268]
Siema,
Dzikoysk czy możesz dodać do pluginu zmienne: Ranking gracza i Tag gildii które można użyć w pluginach do chatu?

**Comment by Dzikoysk** [comment]
Są:
* {TAG}
* {RANK}
* {POINTS}

**Comment by SkymaxPlay** [comment]
Ok nie wiedziałem :) Mam jedno pytanie czy dodasz że gdy gracz się wyloguje podczas walki to dostanie ujemne punkty a ostatni atakujący dostanie za niego ranking tak jak by go zabił lub poprostu jakaś wartość wpisana w configu

**Comment by Dzikoysk** [comment]
Mam to w planach, na razie możesz użyć CombatLog :)

**Comment by SkymaxPlay** [comment]
To mogę dodać do CombatLog'a  że łączy się z bazą MySQL i zabitemu usuwa punkty za logniecie.

**Comment by Dzikoysk** [comment]
Jak CombatLog wykryje, że ktoś się wylogował, to na czacie wyświetli się normalnie, że gracz został zabity przez i zostaną odjęte punkty

**Comment by SkymaxPlay** [comment]
Widziałem coś w configu o atakującym. Tak samo jak w twoim pluginie tylko nie bylem pewien bo oglądałem to w szkole :P
