### ISSUE TITLE
Dodanie {TAG} {RANK} {POINTS} w pluginie?

### ISSUE THREAD

**Issue by LuxarPL** [Dzikoysk/FunnyGuilds#269]
Chciałbym napisać plugin na chat i czy chciałem się zapytać jak dodać {TAG} {RANK} {POINTS} w pluginie?

**Comment by Dzikoysk** [comment]
Dodaj te tagi do formatu, fg sam je znajdzie i podmieni. Tylko ustaw sobie wyższy priorytet wydarzenia.

**Comment by LuxarPL** [comment]
Wyższy priorytet, czyli? (jestem zielony)

**Comment by Dzikoysk** [comment]
Jeżeli już, to LOWEST :P
