### ISSUE TITLE
bug i propozycja

### ISSUE THREAD

**Issue by zorro8003PL** [Dzikoysk/FunnyGuilds#271]
1. Nie działa to że gildia która ma mniej niż 4 członków nie jest liczona w topce
2. Dodaj do configu ile musi być minimum członków w gildii aby gildia była liczona w topce

**Comment by Dzikoysk** [comment]
Na razie nie dodam tego do cfg, bo 99% osób nie chce się dla jednej funkcji aktualizować całego configu

**Comment by zorro8003PL** [comment]
a, ok
