### ISSUE TITLE
Poszukuję osoby znającej się na programowaniu (edytowanie .java i zamiana na .class)

### ISSUE THREAD

**Issue by CzlowiekKuktas** [Dzikoysk/FunnyGuilds#275]
Witam.

jeśli ktoś zna się trochę na javie i może mi pomóc edytować trochę plik .java i zmienić go na .class to proszę o wiadomość PW. :)

**Comment by TheMolkaPL** [comment]
Co to ma do FunnyGuilds?
GitHub to Issue Tracker, nie tablica ogłoszeń...

**Comment by CzlowiekKuktas** [comment]
Dzikoyska i tak nie ma, więc taka prośba zamieszczona tutaj nikomu nie powinna przeszkadzać. :)

**Comment by TheMolkaPL** [comment]
To, że go niema to nie oznacza, że można robić spam w Issue Trackerze jego projektu... :bulb:

**Comment by CzlowiekKuktas** [comment]
Robię jakiś spam?

**Comment by TheMolkaPL** [comment]
> Poszukuję osoby znającej się na programowaniu (edytowanie .java i zamiana na .class)

**Comment by CzlowiekKuktas** [comment]
Dobra morda tam, bo spam robisz tylko ty.

**Comment by zorro8003PL** [comment]
Usuń ten issue

**Comment by CzlowiekKuktas** [comment]
Kim ty jesteś, żeby mi mówić takie rzeczy? Kultury trochę.

**Comment by zorro8003PL** [comment]
Twoim Panem

**Comment by CzlowiekKuktas** [comment]
ty kurwo

**Comment by zorro8003PL** [comment]
Nie mów do mnie jak do Ojca.

**Comment by CzlowiekKuktas** [comment]
Zapraszam na tsa syneczku.

**Comment by TheMolkaPL** [comment]
@CzlowiekKuktas proszę zachować kulturę osobistą.

**Comment by CzlowiekKuktas** [comment]
Morda, konwersację skończyłem na samym początku, zamknąłem temat, tylko jakiś debil się wpierdala.

**Comment by zorro8003PL** [comment]
debil to Twój stary, ten jeden i drugi.

**Comment by CzlowiekKuktas** [comment]
Jesteś chyba niekompetentny, żeby udzielać się publicznie.

**Comment by zorro8003PL** [comment]
Tak Cię na obiad wołają
