### ISSUE TITLE
[PROPOZYCJA] /itemy i dzwieki

### ISSUE THREAD

**Issue by TheMrkoia** [Dzikoysk/FunnyGuilds#278]
Dodanie komendy /itemy w nowych wersjach :)  i dzwieki jak sie podbije gildie.

**Comment by CzlowiekKuktas** [comment]
Dźwięki można dodać, a komendę /itemy już nie. :)

**Comment by TheMrkoia** [comment]
CzlowiekKaktus nie pisalem do ciebie bo chyba ty pluginu nie robiles?..

**Comment by CzlowiekKuktas** [comment]
:cactus: 
Idiota...

**Comment by TheMolkaPL** [comment]
Akurat mi pomysł z dźwiękami się podoba :P

**Comment by CzlowiekKuktas** [comment]
To nie pomysł tylko propozycja - pomysł to miał mc.****.net
