### ISSUE TITLE
Tag gildii na chacie i w wiadomościach o śmierci

### ISSUE THREAD

**Issue by ghost** [dzikoysk/FunnyGuilds#283]
Witam,

mógłbyś podzielić pokazywanie tagu na takie coś?

Tag gildii wyświetlany w wiadomościach na chacie.
chat-guild: &7[&b{TAG}&7}
Tag gildii wyświetlany w wiadomościach po śmierci.
death-guild: &7[&4{TAG}&7}

:cactus:

**Comment by zorro8003PL** [comment]
dobry pomysł
