### ISSUE TITLE
Dodanie zmiennej

### ISSUE THREAD

**Issue by Mroczny337** [dzikoysk/FunnyGuilds#285]
Cześć, fajnie było by dodać zmienną {ATTACKER-ITEM} np.
rankDeathMessage: '{VTAG}&c{VICTIM} zostal zabity przez {ATAG}&c{ATTACKER} &8[&6+{+}&8]&c za pomoca {ATTACKER-ITEM}'

**Comment by Mroczny337** [comment]
wow po roku xD

**Comment by dzikoysk** [comment]
To chyba nawet zostało dodane! xD

**Comment by artur9010** [comment]
# Wykop roku!

![image](https://cloud.githubusercontent.com/assets/4835677/21083677/09391686-bff6-11e6-933d-258bb0d5a881.png)

**Comment by TheMolkaPL** [comment]
@artur9010 To moja grafika :(
