### ISSUE TITLE
Tytuły

### ISSUE THREAD

**Issue by KaVzaQ** [dzikoysk/FunnyGuilds#287]
Dodaj możliwość ustawienia tytułów na chacie gildyjnym.

Np zmienna {TITLE} w chatach.
i wtedy komenda /tytul <gracz> <jakis tytul>

Mogło by być fajne, coś w stylu titlesów w factions.

PS: Co to za "poważny błąd" w ostatniej aktualizacji? Warto by było wiedzieć :D

**Comment by TheMolkaPL** [comment]
FunnyGuilds obecnie nie wspiera Minecraft 1.8.

**Comment by AdamGrzegorz** [comment]
Wiem że nie wspiera, ale co to ma wspólnego z poprawieniem "poważnego błędu"?

a te titlesy to wiesz o co chodzi np. [Chat gildyjny] [Tytul ustawiony przez lidera] Gracz: tekst

**Comment by alvenplay** [comment]
Gracz miał uprawnienia do /funnyguilds save-all :)
