### ISSUE TITLE
topka graczy

### ISSUE THREAD

**Issue by zorro8003PL** [dzikoysk/FunnyGuilds#288]
Czasami do topki graczy przy nickach dodają się dodatkowe znaki np. jak ktoś ma nick Lolek19 to czasami jest Lolek19ou ale po relogu poprawia się a potem po jakimś czasie znowu tak jest

**Comment by Wruczek** [comment]
To przez scoreboardy. Dzieje się to tylko gdy zmieni się ranking. Końcówka nicku gracza zrobiona przez scoreboard zostaje, a ranking się przesuwa...
