### ISSUE TITLE
[Propozycja] Dodanie zmiennej do wiadomosci po smierci!

### ISSUE THREAD

**Issue by xW0LFx** [dzikoysk/FunnyGuilds#293]
Dodanie zmiennej np: {NAME} do wiadomości po zabiciu gracza:
Gracz Dzikoysk (-10) został zabity przez Janusz (+10) z przedmiotu: diamentowy miecz [Tutaj nazwa itemku!]

**Comment by TheMolkaPL** [comment]
Ale gdy przykładowo ten miecz nie będzie miał nazwy własnej? Ma wyświetlić `DIAMOND_SWORD`?

**Comment by zorro8003PL** [comment]
to niech będzie:
deathmessage1: Dzikoysk (-10) zostal zabity przez Janusz (+10)
deathmessage2: Dzikoysk (-10) zostal zabity przez Janusz (+10) z przedmiotu: diamentowy miecz
deathmessage3: Dzikoysk (-10) zostal zabity przez Janusz (+10) z przedmiotu: diamentowy miecz [nazwa przedmiotu]

**Comment by TheMolkaPL** [comment]
Tylko skąd plugin będzie wiedział, że item `DIAMOND_SWORD` to `diamentowy mecz`?
Można ewentualnie to tłumaczyć na `diamond sword` :+1:

**Comment by kukubaczek** [comment]
Po prostu replace "sword" na "miecz" replace "diamond" na "diamentowy" i jest :D

**Comment by TheMolkaPL** [comment]
> Po prostu replace "sword" na "miecz" replace "diamond" na "diamentowy" i jest :D

`DIAMOND_AXE` -> `diamentowy siekiera` :D

**Comment by Dzikoysk** [comment]
Powodzenia :D http://jd.bukkit.org/rb/apidocs/org/bukkit/Material.html

**Comment by zorro8003PL** [comment]
Dzikoysk zrób tylko te podstawowe jak np. diamentowy miecz siekiera łopata itp.. po co wszystko zmieniać

**Comment by TheMolkaPL** [comment]
> Powodzenia :D http://jd.bukkit.org/rb/apidocs/org/bukkit/Material.html (A to przecież nie wszystkie)
> Dzikoysk zrób tylko te podstawowe jak np. diamentowy miecz siekiera łopata itp.. po co wszystko zmieniać

Może wygodniej będzie plik (przykładowo properties) w którym kluczem będzie item z Material Bukkita, a wartością nazwa własna.

Technicy sami będą ustalać jakie itemy będą mieć nazwy ustawiając ich wartości.

```java
Properties properties; // plik properties
ItemStack item; // item

String itemName = properties.getProperty(item.getType().toString());
if (itemName != null) {
    // wyświetlanie nazwy
}
```

**Comment by Dzikoysk** [comment]
Myślałem już na dym kiedyś, ale na tym się skończyło (do wyświetlania itemków wymaganych na gildie) :D Zobaczy się, na razie i tak nie chce mi się nic dodawać

**Comment by zorro8003PL** [comment]
to popraw błędy chociaż (te które ja napisałem w innych issues)

**Comment by Dzikoysk** [comment]
Jak mam czas, to poprawiam i wrzucam

**Comment by zorro8003PL** [comment]
:)
