### ISSUE TITLE
Możliwość wybrania nicku poprzez kliknięcie TAB

### ISSUE THREAD

**Issue by kepo70** [dzikoysk/FunnyGuilds#295]
Dodał byś możliwość wybrania nicku gracza (np wpisuje a (nastepnie klikam Tab) i wybiera mi gracza np Adam. Wiem że teraz tego niema ;) i trzeba np ./zapros (recznie wpisywać nick)

**Comment by TheMolkaPL** [comment]
To się nazwywa `Tab completer` :star:

**Comment by kepo70** [comment]
Nie zmam się na tym tak jak ty ;)
