### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by TheFun1337** [Dzikoysk/FunnyGuilds#296]
Witam otóż znalazłem bug w najnowszej wersji FunnyGuilds ponieważ mam zainstalowany plugin i jest na zielono w /plugins a gdy pisze /g nie znaleziono komendy ;/ prosze o pomoc.

**Comment by daanioo** [comment]
Ja też mam ten problem !

**Comment by TheMolkaPL** [comment]
Podajcie log z konsoli na [pastebin](http://pastebin.com).

**Comment by TheFun1337** [comment]
moje logi: http://pastebin.com/ZyKAKBP9

**Comment by TheMolkaPL** [comment]
Musisz stworzyć plik bazy danych w `FunnyGuilds/data/funnyguilds.dat`
