### ISSUE TITLE
chat 

### ISSUE THREAD

**Issue by michaa2029** [dzikoysk/FunnyGuilds#297]
Siemka ktoś wie jak zrobić by na chacie gildi była jej nazwa oraz ranking?

robiłem w essentials chat oraz w chat manager i nie pomogło pisałem np.
&2[&6{TAG&2} I nie działało ktoś wie jak takie coś zrobić?

**Comment by Dzikoysk** [comment]
W essChat dajesz tylko:
* {TAG} dla tagu gildii
* {RANK} dla pozycji w rankingu
* {POINTS} dla punktów gracza
