### ISSUE TITLE
Błąd podczas tworzenia gildi

### ISSUE THREAD

**Issue by MrFretko** [dzikoysk/FunnyGuilds#299]
Jak ktos tworzy gildie to go wywala i pisze mu to http://scr.hu/1vne/p7n7h
a potym nie moze wejsc

**Comment by TheMolkaPL** [comment]
Scoreboard

**Comment by MrFretko** [comment]
? ;p

**Comment by TheMolkaPL** [comment]
Jakiś błąd scoreboardu.

**Comment by MrFretko** [comment]
a jak go naprawić?

**Comment by MrFretko** [comment]
kur. ktos odpowie>?
przez to trace 30+ graczy -,-

**Comment by Sztandar18** [comment]
Zbyt długa nazwa tagu+nicu? W scoreboardzie jest limit 16, tu gracze powodują problem, nie plugin :P Ogranicz długość tagu do 4 i będzie ok.

**Comment by Dzikoysk** [comment]
Podaj pluginy

**Comment by Wruczek** [comment]
@Dzikoysk Nie pluginy lecz config. Problem prawdopodobnie leży w zbyt długiej nazwie gildii, np: "Twoja gildia: {GILDIA}" = więcej niż 16 znaków, ponieważ zostanie wyświetlona pełna nazwa a nie tag gildii.

**Comment by Dzikoysk** [comment]
To samo może powodować czasem NameTagEdit.

Tak swoją drogą to ciekawe, bo fg teoretycznie sprawdza długość już po podmianie :thought_balloon:

**Comment by Wruczek** [comment]
W tabliście jest jakiś z tym problem, sam go miałem.

**Comment by xVacuum** [comment]
Jak gildia dodaje się do top10, i nazwa jest za długa, to przekracza dowolną ilość znaków, i serwer nie pozwala odczytać tablisty i wywala błąd. Musisz usunąć tą gildie ręcznie, lub zmienić coś w tabliscie, inaczej się nie da.

**Comment by Wruczek** [comment]
@xVacuum Napisałem to 2 posty wyżej...
