### ISSUE TITLE
Błędy w FG.

### ISSUE THREAD

**Issue by ikill4fun** [Dzikoysk/FunnyGuilds#302]
Otworzyłem nową edycję swojego serwera.
Wszystko było dobrze, puki gracze nie stworzyli gildii.
Regiony gildii (claimy) nie działają, każdy gracz może zniszczyć gildie, w dodatku, cała konsola jest zasypana errorami z tego pluginu.

Errory: http://pastebin.com/pzqc0uVb

Proszę o pomoc, gdyż utrudnia to grę i laguje serwer.

**Comment by Dzikoysk** [comment]
Zakładam, że źle zrobiłeś config, podaj no go tutaj ;)

**Comment by ikill4fun** [comment]
Już wszystko jest w porządku.

2015-02-15 0:48 GMT+01:00 Dzikoysk <notifications@github.com>:
