### ISSUE TITLE
Propozycja nowego systemu rankingu

### ISSUE THREAD

**Issue by Sztandar18** [dzikoysk/FunnyGuilds#303]
W pluginie RevoGuild (który nie jest wspierany przez autora) system rankingu był rozwiązany w ten sposób:
  algorithm:
    ranking:
      win: (300 + (({KILLER_POINTS} - {PLAYER_POINTS}) \* (-0.2)))
      lose: Math.abs({WIN_POINTS}/2)

Czyli wyglądało to tak, osoba która zabiła gracza dostawała punkty na podstawie:
300 + PUNKTY_ZABÓJCY - PUNKTY_ZABITEGO \* (-0.2)

Zaś osoba, która została zabita traciła połowę punktów gracza, który ją zabił.
Jak widać, w tym pluginie było można konfigurować to samodzielnie, jednak nie jest on wspierany i posiada błędy wykluczające jego używanie, dobrze by było gdybyś Ty dzikoysk, albo na stałe dodał taki system rankingu w kodzie lub także spróbował stworzyć taką opcję konfiguracji jak autor RevoGuild.

**Comment by Sztandar18** [comment]
Co sądzicie o takim rozwiązaniu?

**Comment by AdamGrzegorz** [comment]
Ja jestem za wprowadzeniem nowej opcji w configu:

Ranking-math-win/lose: <własne obliczenia rankingu>
Wtedy każdy zrobił by sobie jak chce :)

**Comment by Sztandar18** [comment]
Oczywiście dla użytkownika pluginu muszą być dostępne jakieś globalne zmienne tak jak w RevoGuild, najlepsze rozwiązanie :)
