### ISSUE TITLE
Najnowsza aktualizacja

### ISSUE THREAD

**Issue by CzlowiekKuktas** [Dzikoysk/FunnyGuilds#305]
Co dokładnie dodaje najnowsza aktualizacja?

**Comment by Dzikoysk** [comment]
Tzn? Generalnie wszystko opisałem pod aktualizacją

**Comment by TheMolkaPL** [comment]
Patrz fe42ce076a3ab590058128b78c9343ba0e464350 i [changelog](https://github.com/Dzikoysk/FunnyGuilds/releases).

**Comment by CzlowiekKuktas** [comment]
Cos zwiazanego z pluginem Skript czy nie?

**Comment by TheMolkaPL** [comment]
Nie, z [Panda](https://github.com/Dzikoysk/Panda)...

**Comment by CzlowiekKuktas** [comment]
No fajnie, a co to jest?

**Comment by TheMolkaPL** [comment]
Przeczytaj README to zobaczysz.

**Comment by Dzikoysk** [comment]
Na razie wprowadza to tylko configi i refleksje (prościutkie). 

Przykładowy skrypt refleksji:

```c net.dzikoysk.funnyguilds.listener.PlayerDeath >> victimCooldown = 0L```

**Comment by CzlowiekKuktas** [comment]
To sie wpisuje do configu czy co? Sorry chlopaczki, ale ja zielony w tych sprasacg. :cactus:

**Comment by CzlowiekKuktas** [comment]
Sprawach* (telefon)

**Comment by Dzikoysk** [comment]
Tworzysz nowy plik w folderze "scripts" , np. "Cooldown.reflect"

**Comment by CzlowiekKuktas** [comment]
No i jak zmienić na przykład to:

StringUtils.replace(Settings.getInstance().chatGuild, "{TAG}", victim.getGuild().getTag()));

na to:

StringUtils.replace(Settings.getInstance().chatGuild, "&6{TAG}", victim.getGuild().getTag()));

**Comment by Dzikoysk** [comment]
Bez przesady, aż tyle się zrobić nie da :D

 Fajnie będzie, jak dodam możliwość edytowania zmiennych należących do obiektów (co pozwoli edytować np. dane gildii, graczy itd.)

**Comment by CzlowiekKuktas** [comment]
To słabo. :cactus: 
Jakbym wiedział, jak zrobić plik .class to bym sam zmienił. :cactus:

**Comment by TheMolkaPL** [comment]
@CzlowiekKuktas kompilujesz z .java

**Comment by CzlowiekKuktas** [comment]
Jak?

**Comment by Dzikoysk** [comment]
@CzlowiekKuktas jak nie potrafisz korzystać, to słabe :D To, że Java na to nie pozwala (chyba, że edycja kodu bajtowego) to inna sprawa ;)

**Comment by CzlowiekKuktas** [comment]
No a co możesz zmienić? Jak nie takich rzeczy jak napisałem to raczej nieprzydatne. :cactus: 
Jak z edytować .java i zrobić z tego .class?

**Comment by Dzikoysk** [comment]
Połowa fg leci na refleksjach, ale masz rację, nie przydatne xD

Masz source, wrzucasz do siebie i tyle

**Comment by CzlowiekKuktas** [comment]
Nie znam się na takich rzeczach. :cactus: 
No mam source, jak edytować .java i skompilować na .class?

**Comment by Dzikoysk** [comment]
Weź ogarnij sobie jakiś tut, bo to podstawy :smile:

**Comment by CzlowiekKuktas** [comment]
Chujowo tłumaczą, możesz zalinkować jakiś dobry, gdzie będzie to wytłumaczone? :cactus:

**Comment by TheMolkaPL** [comment]
[Proszę...](http://docs.oracle.com/javase/tutorial/)

**Comment by CzlowiekKuktas** [comment]
Dzięki, nie przydało się.
