### ISSUE TITLE
Problem z TAB

### ISSUE THREAD

**Issue by kepo70** [Dzikoysk/FunnyGuilds#306]
Jak to naprawić? http://scr.hu/26i9/4ytpx

**Comment by TheMolkaPL** [comment]
Zobacz #288

**Comment by kepo70** [comment]
No jak to jest ten sam błąd.

**Comment by TheMolkaPL** [comment]
Skoro ten sam to nie rób nowego issue...

**Comment by Dzikoysk** [comment]
https://github.com/Dzikoysk/FunnyGuilds/issues/203

**Comment by kepo70** [comment]
Nie rozumiesz mnie wgl.. Mówię że to jest odrębnie inny błąd.

**Comment by Dzikoysk** [comment]
Czym się różni? Bo ja jakoś nie widzę, walnięte kodowanie w /data/playerlist.yml

**Comment by Sztandar18** [comment]
Ja tam nie mam z tym pluginem żadnych problemów, działa dobrze na 200 slotowym serwerze.
