### ISSUE TITLE
Podbijanie gildii za pomocą Huzuni

### ISSUE THREAD

**Issue by Sztandar18** [dzikoysk/FunnyGuilds#308]
Dziś jeden z graczy zgłosił mi, że gildie można podbić za pomocą FreeCam'a zawartego np. w Huzuni. Wystarczy ustać na terenie gildii, włączyć czit i lecieć do kryształu i go kliknąć, dałoby się coś z tym zrobić?

**Comment by TheMolkaPL** [comment]
FreeCam działa tylko po stronie klienta. Nie jest możliwe kliknięcie bloku, ani entity poza zasięgiem - zainstaluj plugin NoCheatPlus.

**Comment by Dzikoysk** [comment]
Pomyślę nad jakimś zabezpieczeniem /play nyan

**Comment by Sztandar18** [comment]
To dlaczego gracze mi zgłaszają, że jest to możliwe i że w poprzednich wersjach nie dało się w ten sposób podbijać? NoCheatPlus mam od samego początku istnienia serwera.

**Comment by Dzikoysk** [comment]
Pewnie jest to możliwe od 3.9+, bo wtedy crystale przeszły na packety. Ncp pewnie nie za wiele na do powiedzenia wtedy

**Comment by sokrates1231** [comment]
Ja już to dawno temu zgłaszałem tobie dzikoysk ;). A ty nie wiedziałeś co to Freecam i tłumaczyłem...

**Comment by kepo70** [comment]
DA SIE PODBIC GILDIE FREECAMEM TheMolka ty chyba wgl w mc nie grasz.

**Comment by TheMolkaPL** [comment]
Gram, ale w 90% na localhoście. ;) Coś musieli niedawno zmienić w działaniu tego ;)

**Comment by kepo70** [comment]
I musza to naprawić bo gracze podbijają sobie gildie................... ale co wyjdzie update ale tego nie naprawi ;)

**Comment by TheMolkaPL** [comment]
Jak to muszą? Przecież gildie pisze @Dzikoysk xd

**Comment by domin07** [comment]
Mam nadzieję @Dzikoysk że, to naprawisz bo teraz prawie każdy używa huzuni a takie informacje że, gildie można podbić za pomocą tego cheata roznoszą się bardzo szybko... Oj, bardzo szybko...

**Comment by Dzikoysk** [comment]
Sprawdźcie #3.9.9.1

**Comment by an0nim0wy** [comment]
Fixed.
