### ISSUE TITLE
Gracze podbijają gildie nie dotykając crystala. 

### ISSUE THREAD

**Issue by kepo70** [Dzikoysk/FunnyGuilds#313]
Niewiem co to za bug ale gracz z przeciwnej gildii może podbić gildie nie wbijając się do środka

**Comment by Sztandar18** [comment]
Już to zgłaszałem: https://github.com/Dzikoysk/FunnyGuilds/issues/308

**Comment by kepo70** [comment]
TO JEST BŁAD KTÓRY NIE POWINIEN SIE POJAWIC!

**Comment by kepo70** [comment]
FreeCamem da sie podbic gildie ;) - testowane ;D
