### ISSUE TITLE
Tab sie buguje 

### ISSUE THREAD

**Issue by lukas3221** [dzikoysk/FunnyGuilds#314]
Witam po wklejeniu takiego player list tab wyglada tak : http://prntscr.com/69lv0a . Wklejalem inne player list i wygladalo podobnie  
player-list:
  1: '&8----------------'
  2: '&8----------------'
  3: '&8----------------'
  4: '    &9TOP Graczy'
  5: '   &cInformacje'
  6: '     &9TOP Gildii'
  7: '&8----------------'
  8: '&8----------------'
  9: '&8----------------'
  10: '&71. &f{PTOP-1}'
  11: '       &9Online'
  12: '&71. &c{GTOP-1}'
  13: '&72. &f{PTOP-2}'
  14: '      &2{ONLINE} &7/ &260'
  15: '&72. &c{GTOP-2}'
  16: '&73. &f{PTOP-3}'
  17: '&8----------------'
  18: '&73. &c{GTOP-3}'
  19: '&74. &f{PTOP-4}'
  20: ''
  21: '&74. &c{GTOP-4}'
  22: '&75. &f{PTOP-5}'
  23: ''
  24: '&75. &c{GTOP-5}'
  25: '&76. &f{PTOP-6}'
  26: '&7Nick: &f{PLAYER}'
  27: '&76. &c{GTOP-6}'
  28: '&77. &f{PTOP-7}'
  29: '&7Zabojstwa: &f{KILLS}'
  30: '&77. &c{GTOP-7}'
  31: '&78. &f{PTOP-8}'
  32: '&7Smierci: &f{DEATHS}'
  33: '&78. &c{GTOP-8}'
  34: '&79. &f{PTOP-9}'
  35: '&7Punkty: &f{POINTS}'
  36: '&79. &c{GTOP-9}'
  37: '&710. &f{PTOP-10}'
  38: '&7Gildia: &f{TAG}'
  39: '&710. &c{GTOP-10}'
  40: '&711. &f{PTOP-11}'
  41: ''
  42: '&711. &c{GTOP-11}'
  43: '&712. &f{PTOP-12}'
  44: ''
  45: '&712. &c{GTOP-12}'
  46: '&713. &f{PTOP-13}'
  47: ''
  48: '&713. &c{GTOP-13}'
  49: '&714. &f{PTOP-14}'
  50: ''
  51: '&714. &c{GTOP-14}'
  52: '&715. &f{PTOP-15}'
  53: ''
  54: '&715. &c{GTOP-15}'
  55: '&8----------------'
  56: '&8----------------'
  57: '&8----------------'
  58: '&7Strona: &fBrak'
  59: '&7TS3: &fBrak'
  60: '&7Ranga: &f/vip'

**Comment by Dzikoysk** [comment]
Musisz ustawić 60 slotów na serwerze

**Comment by lukas3221** [comment]
Dzieki zadziałało
