### ISSUE TITLE
Do następnego Update <3

### ISSUE THREAD

**Issue by Szeder32** [dzikoysk/FunnyGuilds#316]
DO NASTĘPNEGO UPDATE DODAJ:

• Za pomocą zapalniczki można podpalać drewno i inne z tym związane rzeczy!
• Poprawienie w itemach na gildie (nie można dać koxów[golden apple:1])

BĘDĘ DODAWAŁ JAK MI COŚ PRZYJDZIE DO GŁOWY <3

POZDRO PEPSIKOLA

**Comment by Dzikoysk** [comment]
kox: Enchanted Golden Apple
