### ISSUE TITLE
Kilka dodatków 

### ISSUE THREAD

**Issue by xKendu** [dzikoysk/FunnyGuilds#317]
Możliwość wyłączenia podbijania/wygasania/ilości rankingu w tagu nad głową/ wyświetlanie rankingu po kliknięciu na gracza/tworzenia cuboidu[serwery pvp. 
Dodaj zmienna {ADMIN, która w systemie banowania będzie wyświetlać przez kogo gildia została zbanowana

**Comment by Dzikoysk** [comment]
Z tego co wymieniłeś nie ma chyba tylko możliwości wyłączenia regionów i tagu {ADMIN} :lollipop:

**Comment by xKendu** [comment]
Nie ma możliwości wyłączenia podbijania/wygasania są jedynie takie opcje http://scr.hu/51z1/61plr i wyświetlanie rankingu po kliknięciu, jest tylko przy kliknięciu z shift http://scr.hu/51z1/c7ktc, a wyłączenie rankingu w tagu nad głową nie zauważyłem :P

**Comment by Dzikoysk** [comment]
Podbijanie - zmień blok w centrum gildii
Wygasanie - czas na 0, albo na jakiś bardzo długi xd

**Comment by xKendu** [comment]
a ranking? XDD

**Comment by xKendu** [comment]
a ranking po kliknieciu na gracza?

**Comment by Dzikoysk** [comment]
Tego w sumie tak zupełnie wyłączyć się nie da
