### ISSUE TITLE
combatlog i ranking

### ISSUE THREAD

**Issue by SkymaxPlay** [dzikoysk/FunnyGuilds#319]
Siema,
Wgrałem combatloga gdy ktoś się wyloguje to zabija go ale nie dodaje rankingu do gracza i nie odejmuje. Czy w ogóle gildie z tym pluginem działają? Jeśli nie do masz jakiś który działa?

**Comment by TheMolkaPL** [comment]
CombatLog nie będzie działać ponieważ on nie zabija gracza. @Dzikoysk ma w planach napisanie anty-logouta w FunnyGuilds. #131
