### ISSUE TITLE
Chat bez Essentials?

### ISSUE THREAD

**Issue by xVacuum** [Dzikoysk/FunnyGuilds#320]
Nie używam na serwerze Essentialsa tylko autorskich toolsów, i mam problem.
Albowiem gdy tworzę samemu format chatu i wstawiam tam {TAG} to nie zbyt chce działać (po kodzie patrzyłem że on replacuje coś na coś z chatu, ewidentnie tak to nie działa jak chciałem)

Czy jest jakaś inna możliwość stworzenia chatu? Autorski plugin raczej odpada, bo nawet próbowałem FunnyGuildsa zaimportować i wstawić tam oryginalną formułkę getTag, niestety próba skończyła się błędem NullPointerException. 

Proszę o pomoc, bo jest to dla mnie cholernie ważne.

**Comment by TheMolkaPL** [comment]
Nie wiem co Ci nie chce działać. Ustawiasz setFormat(...) w AsyncPlayerChatEvent i gitara. https://github.com/Dzikoysk/FunnyGuilds/blob/master/src/net/dzikoysk/funnyguilds/listener/PlayerChat.java#L36

**Comment by xVacuum** [comment]
Próbowałem, mam ten kod: 
http://pastebin.com/raw.php?i=f3Wa4HEg

Na chacie i tak jest {TAG} {POINTS} :C

**Comment by TheMolkaPL** [comment]
^^ Nie tak ustawia się nick gracza i wiadomość, używaj `%s` ;)

**Comment by xVacuum** [comment]
Po zmianie i tak nie działa.
Na chacie mam {TAG} i {POINTS} :C

**Comment by xVacuum** [comment]
Proszę o pomoc :/
Potrzebuje tego koniecznie na dzisiaj :C

**Comment by Dzikoysk** [comment]
Wszystkie te wasze tools'y są zawsze takie dobre i potrzebne... xD

Zmień priorytet wydarzenia

**Comment by xVacuum** [comment]
Na jaki? Miałem najwyzszy i ni dziala
