### ISSUE TITLE
Aktualizacja 4.0

### ISSUE THREAD

**Issue by Dzikoysk** [Dzikoysk/FunnyGuilds#322]
Pracuję nad wersją 4.0, więc możecie pisać o wszystkim - czego brakuje, co zmienić, a co usunąć. Ja sobie to później przejrzę, żeby mieć jakiś ogólny zarys i coś tam się pewnie doda :)

**Comment by RamboLc** [comment]
To co napewno brakuje w tym pluginie to Ogarniety ranking Gildii (do TOP GILDII niech zalicza tylko te gildie co mają powyżej np 4 członków), bo to jest bezsensu, ze jakiś gosciu z wieksza iloscia pkt założy sb gildie i jest 1-szy w TOP ;)

W skrócie:

- Umieszczanie w "TOP GILDII" gildii powyżej 4 graczy

**Comment by zorro8003PL** [comment]
Popraw:
1. Jak ktoś jest w gildii i opuści gildie to inni gracze z tej gildii widzą siebie na czerwono
2. jak ktoś dołącza do gildii i jeśli ta gildia ma sojusz z inną gildią to nie zmienia się kolor sojuszników
3. jak ktoś opuści gildie i jeśli ta gildia ma sojusz z inną to nie zmienia się kolor sojuszników na czerwony
4. Sojusze. Że jak jedna gildia ma sojusz z drugą to czasami w /info u tej pierwszej gildii pisze że ta druga gildia nie ma sojuszu z tą pierwszą.
5. Członkowie gildii -> http://scr.hu/19xy/36b1e
Dodaj:
1. Wiadomości globalne (broadcast) jak:
    - jedna gildia z drugą przystępują do sojuszu
    - jak nowy gracz jakiejś gildii zostaje nowym liderem
    - jak jedna gildia z drugą zrywa sojusz
2. Do configu możliwość zmienienia w messages.yml zmiennej {V-TAG} i {A-TAG} czyli tagi gildii victim'a i attacker'a.

**Comment by SkymaxPlay** [comment]
Dodaj anty-logout'a

**Comment by TheMrkoia** [comment]
Dodaj dzwieki jak sie podbija gildie :)

2015-03-26 15:17 GMT+00:00 SkymaxPlay <notifications@github.com>:

**Comment by Dzikoysk** [comment]
Jakieś konkretne? :)

**Comment by Kuba5555** [comment]
Jest szansa zebys niebawem dodal wsparcie dla spigota 1.8.1?

**Comment by Dzikoysk** [comment]
Hmmmm... Nie wiem

**Comment by zorro8003PL** [comment]
Dodaj może wsparcie do vanisha z Essentials czy tam VanishNoPacket, bo można łatwo zobaczyć czy ktoś jest na vanishu na serwerze ponieważ np. na komende /list pokazuje że jest 10 graczy (+1 ukryta osoba z vanishem) a na TAB'ie z FunnyGuilds pokazuje że jest 11 osób. To można łatwo zobaczyć że 1 osoba jest na serwerze na vanishu.

**Comment by TheMolkaPL** [comment]
Wsparcie VanishNoPacket można dodać bardzo łatwo bez potrzeby dodawania VNP do projektu. Po prostu sprawdzając w API Bukkita czy ten gracz jest ukryty.

Co do Essentials to mogą być oczywiście problemy, bo on po prostu.... nie działa...
Vanish w Essentials działa na zasadzie dawania potki invisible.

**Comment by CzlowiekKuktas** [comment]
Dobry AntyLogout, własny kalkulator ELO, dodawania/odejmowania rankingu. 
Do tego: #283 + #284

**Comment by xVacuum** [comment]
Losowanie efektu dla gildii, /efekt i losuje dla całej gildii określone w configu efekty potek.
Mogłoby być zarypiste :D

**Comment by domin07** [comment]
Kamienne cegły nie niszczą się pod wpływem TNT gdy są oblane wodą a inne bloki tak. Trzeba to naprawić ;).

**Comment by SkymaxPlay** [comment]
Ja zrobiłem własnego vanisha na serwerze i działa świetnie. Jest o wiele lepszy od vanisha w esentials. Gracz jest całkowicie nie widoczny kiedy ma zbroję i efekty mikstur. Ne dodaje efektu niewidzialności i dodatkowo dodaje bar z dragonem który informuje że gracz jest niewidoczny dla innych :D

**Comment by SkymaxPlay** [comment]
Woda się nie niszczy podczas wybuchu, przynajmniej u mnie :|

**Comment by zorro8003PL** [comment]
@UP. U mnie też nie xd

**Comment by CzlowiekKuktas** [comment]
Przy używaniu komend z tagiem (np. /dolacz test), gdy tag wpiszemy z malych liter pojawia sie on rowniez z malych liter na chacie. Powinien sie pokazywac prawdziwy tag.

**Comment by Dzikoysk** [comment]
Wymieniajcie wszystko co wiecie i chcecie, wszystko czytam :3

**Comment by zorro8003PL** [comment]
Dzikoysk jeszcze popraw to że czasami do topki graczy na tabie dodają się dodatkowe losowe znaki do nicków...

**Comment by CzlowiekKuktas** [comment]
O! Popraw porządnie tablistę, bo często przy wchodzeniu na serwer tablista się buguje, dodają się jakieś nicki graczy. Tak jest np. przy bungee.

**Comment by SkymaxPlay** [comment]
Gdy się usunie gildię a jest na tabie to się buduje i nie znikają punkty tej gildii. Jest Brak[1000] coś takiego

**Comment by zorro8003PL** [comment]
SkymaxcPlay, też tak mam xd.

**Comment by Wruczek** [comment]
@TheMolkaPL Potka ma tylko sygnalizować o tym, że mamy włączonego vanisha...

https://github.com/essentials/Essentials/blob/a2c43d822c66e617a84df9a8f074b9c3a3e32fae/Essentials/src/com/earth2me/essentials/commands/Commandvanish.java#L55

https://github.com/essentials/Essentials/blob/d11a295ffd006a6b3edd2c84866b343342e052da/Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java#L284

**Comment by Dzikoysk** [comment]
I teraz pojawia się pytanie: 1.8.x czy 1.7.x?

**Comment by CzlowiekKuktas** [comment]
Oba, ale bardziej pod 1.7.

**Comment by TheMolkaPL** [comment]
@CzlowiekKuktas po co się cofać w rozwoju?

**Comment by CzlowiekKuktas** [comment]
Ty się cofasz w rozwoju, ludzie nie chcą się przenosić tak prędko.

**Comment by Dzikoysk** [comment]
Obu na 100% nie będzie

**Comment by CzlowiekKuktas** [comment]
A Xkleszczers ma :cactus:

**Comment by Dzikoysk** [comment]
Hm?

**Comment by CzlowiekKuktas** [comment]
xcrafters.pl ma na 1.7 i 1.8

**Comment by Dzikoysk** [comment]
I...?

**Comment by CzlowiekKuktas** [comment]
I czemu FG miałoby nie być?

**Comment by Dzikoysk** [comment]
Bo mi się najzwyczajniej nie chce?

**Comment by CzlowiekKuktas** [comment]
A to dużo problemów z tym?

**Comment by Dzikoysk** [comment]
Trochę roboty, której nie lubię, pisanie wielu fragmentów pod obie wersje

**Comment by CzlowiekKuktas** [comment]
To słabo. :cactus: Co cię skłania do dalszej pracy nad FG?

**Comment by Dzikoysk** [comment]
Dobre pytanie :P

**Comment by mikigal** [comment]
1.7  ;)

**Comment by CzlowiekKuktas** [comment]
Tak z ciekawości pytam, czy hajs, czy co? :cactus:

**Comment by TheMolkaPL** [comment]
> Ty się cofasz w rozwoju, ludzie nie chcą się przenosić tak prędko.

Prędko? :clock1: XD

![Minecraft 1.8](http://imgur.com/gxsotop)
https://mojang.com/2014/09/minecraft-1-8-the-bountiful-update/

**Comment by mikigal** [comment]
Jak na polskie serwery to szybko XD

**Comment by CzlowiekKuktas** [comment]
Gościu, ludzie nie chcą się przenosić na 1.8.

**Comment by Zahusek** [comment]
@CzlowiekKaktus ale beda musieli ;)... swiat idzie do przodu, "przyszlosc zaczyna sie dzis" jak kiedys Powiedzial pewien WIELKI Czlowiek ;)... po co Dzikusiowi dokladac kolejne problemy i stosy roboty, a predzej czy pozniej wszyscy beda musieli sie przeniesc na 1.8 i zapewne nastapi to niebawem. Niech Dzikuś zrobi jedna konkretna, porzadna wersje. To pluginy maja dostosowac sie do wymogow serwera, a idac tym tokiem myslenia, trzeba brac pod uwage najnowsza wersje biblioteki bukkita. Minecraft nie zatrzymuje sie na 1.7.x.tylko idzie do przodu. Na 1.7.x konczy sie stary rozdzial bukkita z ktorym byla masa afery, a teraz zaczyna sie nowy rozdzial, z nowymi, lepszymi, sprawniejszymi, metodami oraz opcjami dla graczy ^^. To na jaka wersje wtyczka bedzie stworzona, decyduje programista, sam autor. Ale wydaje mi sie ze nie powinnismy ogladac sie za tyly, bo tamte czasy minely, powinnismy patrzec przyszlosciowo ^^... to tyle co chcialem przekazac ^^.

A tak swoja droga... Siema Dzikuś :D

**Comment by CzlowiekKuktas** [comment]
Co ty pierdolisz? XD Ludzie wolą 1.7 i tyle, 1.8 to można (jeśli w ogóle) robić za parę miesięcy.

**Comment by TheMolkaPL** [comment]
Trochę się tu zamęt zrobił; zamiast pisać jaką wersję to schodzimy do poziomu "co wolą gracze". Lepiej może przenieść tą dyskusję do innego issue (#324), niż pisać go w propozycja do aktualizacji :)

**Comment by Dzikoysk** [comment]
Oki, możecie iść się sprzeczać do "tematu" podanego wyżej, a tutaj dalej zachcianki i błędy :3

Hej Jvmper :> Twoja wypowiedź była za długa i szkoda by ją kasować xd

**Comment by CzlowiekKuktas** [comment]
Propozycje:
Punkty gildii (tablista), ilosc graczy w gildii + online/offline/limit (/info), rozmiar cuboida (/info), kd/ratio gracza (tablista + komenda), zastepca gildii (/info), mozliwosc ustawiania wlasnego koloru graczy offline/online (/info), moze wlasne tagi nad glowa dla administracji itp.? CombatLog obowiązkowo.

Jeśli nie posiadamy gildii lub gildii nie ma w rankingu na tabliscie, informacje nie pokazuja sie.

**Comment by Kuba5555** [comment]
Ej, skoro narazie niema wsparcia dla jakiegos normalnego spigota, to dalby ktos linka do/numer najnowszego wspieranego builda 1.8?

**Comment by Dzikoysk** [comment]
W związku z tym, co działo się w jednym z tematów zawieszam na razie pisanie 4.0 - po prostu straciłem chęci. Zamykam do odwołania.
