### ISSUE TITLE
[WWW] Javadoc

### ISSUE THREAD

**Issue by TheMolkaPL** [dzikoysk/FunnyGuilds#326]
Obecnie na stronie [API FunnyGuilds](http://www.dzikoysk.net/projects/funnyguilds/api/java/) jest wyświetlane jego API. Nie posiada ono jednak żadnych opisów oraz metod. Może lepiej zastąpić tą stronę Javadoc?

Zakładka `Download` na [głównej stronie](http://www.dzikoysk.net/projects/funnyguilds/) także powinna przenosić na [stronę wydań z GitHub](https://github.com/Dzikoysk/FunnyGuilds/releases).

**Comment by Dzikoysk** [comment]
Stronka nie jest skończona, zresztą jak mówiłem, na fg nie mam teraz ochoty :/

**Comment by SlimaKCoder** [comment]
@Dzikoysk dziewczyny szuka. Na pluginy czasu nie ma xD
