### ISSUE TITLE
Top Gildii od kilku osób w gilldii

### ISSUE THREAD

**Issue by domell98** [dzikoysk/FunnyGuilds#328]
Wprowadzenie bycia w topce gildii z minimum np 5 osobami, do ustawienia w configu. Osoby, które mają dużo punktów np. 2 osoby są aktualnie wyżej w rankingu od gildii w której jest 15 osób.

**Comment by RamboLc** [comment]
Takie co pisałem już wiele razy, ale.. ;)
To jest jedyne co brakuje tak na prawde w tych gildiach.
