### ISSUE TITLE
przeniesienie danych z flat do mysql

### ISSUE THREAD

**Issue by SkymaxPlay** [dzikoysk/FunnyGuilds#330]
Siema,
jak przenieść wszystkie pliki z trybu flat do MySQL bez ich utraty.

**Comment by TheMolkaPL** [comment]
FunnyGuilds nie posiada takiej funkcji.

**Comment by SkymaxPlay** [comment]
a komenda /funnyguilds save-all? Dzikoysk coś o tym pisał, wiesz coś o tym?

**Comment by TheMolkaPL** [comment]
To raczej zapisuje wszystkie dane do bazy (plik albo SQL).

**Comment by SkymaxPlay** [comment]
ale czy jak mam 10 graczy na flacie to zapisze za pomocą tej komendy do MySQL?

**Comment by TheMolkaPL** [comment]
Nie, zapisze wszystko co ma obecnie w pamięci do typu bazy która masz w configu.

**Comment by SkymaxPlay** [comment]
ale jak mam np. stare dane we flacie, po restarcie zmienię na MySQL gdy wpiszę tę komendę to wszystko mi się zapisze do bazy razem ze starym

**Comment by Dzikoysk** [comment]
Oczywiście, że możesz przenieść zapis z mysql na flat i odwrotnie. 
* Przy włączonym serwerze włącz w cfg oba zapisy --> /funnyguilds reload --> /funnyguilds save-all --> Wyłącz stary zapis --> /funnyguilds reload
I gotowe

**Comment by SkymaxPlay** [comment]
Wielkie dzięki @Dzikoysk wiedziałem ze coś pisałeś o tej komendzie i o tej funkcji ale nie bylem całkowicie pewien.

**Comment by SkymaxPlay** [comment]
@Dzikoysk nie działa to, można to inaczej to przegrać czy coś?

**Comment by Dzikoysk** [comment]
Czyli coś zrobiłeś źle :C

**Comment by SkymaxPlay** [comment]
Wywalało przez 5 sekund tyle błędów ze nie dali się nic przeczytać. Dodałem bazę takie same dane jak w moim inny pluginie i dalej same błędy.

**Comment by Dzikoysk** [comment]
Podaj błąd, być może plugin się po prostu nie łączy

**Comment by SkymaxPlay** [comment]
Hmm, błąd był taki duzy ze nie da się zobaczyć poczatku w Windows konsoli
Ale wydaje mi się ze się ok powtarza potem ci wysle

**Comment by TheMolkaPL** [comment]
Zobacz plik logów (`latest.log`).

**Comment by SkymaxPlay** [comment]
Aha znowu o tym zapomniałem

**Comment by SkymaxPlay** [comment]
Tutaj masz linka do poprania logów, jak chcesz mogę zrobić skana.
https://www.dropbox.com/s/6nfd55dff3or8xg/logi.txt?dl=0

**Comment by TheMolkaPL** [comment]
Nie masz połączenia z serwerem bazy danych MySQL.

**Comment by SkymaxPlay** [comment]
to powiedz mi jak nie ma, jak mój plugin się łączy na te same passy?

**Comment by TheMolkaPL** [comment]
Ten błąd wiele nie mówi, ale nie masz połączenia z bazą danych.
