### ISSUE TITLE
API

### ISSUE THREAD

**Issue by fejm15** [dzikoysk/FunnyGuilds#331]
Jest moze jakies API do FunnyGuilds? :)

**Comment by TheMolkaPL** [comment]
Coś tam jest ;) http://dzikoysk.net/projects/funnyguilds/api/java/

**Comment by kamcio96** [comment]
http://github.com/kamcio96/KGildieAPI/ :D

**Comment by TheMolkaPL** [comment]
@kamcio96 przecież to API nie ma tu implementacji xd :sob:

**Comment by kamcio96** [comment]
to nie odpowiedz na pytanie :P to propozycja zaiplemetowania w fg :D

**Comment by TheMolkaPL** [comment]
@kamcio96 ja też mam średnio czas niestety :/
