### ISSUE TITLE
Chat - zmienne

### ISSUE THREAD

**Issue by Kenix97** [Dzikoysk/FunnyGuilds#332]
Witam.
Używam FunnyGuilds i chciałbym używać zmiennych takich jak {TAG}.
Jest mały problem otóż nie używam Essentials tylko swoich własnych autorskich Toolsów.
Jak ustawić w e.setFormat zmienną {TAG}? Kiedy ustawiałem ją, nie działała.
Bardzo proszę o odpowiedź.

**Comment by Kenix97** [comment]
Kawałek kodu:

@EventHandler
  public void onChat(final AsyncPlayerChatEvent e) {
    final Player player = e.getPlayer();
    e.setFormat("{TAG}" + player.getDisplayName() + ": " + e.getMessage());

**Comment by xVacuum** [comment]
Zmień priorytet eventu.

**Comment by Kenix97** [comment]
Ustawiłem na HIGHEST i nadal nic..

**Comment by Meehoweq** [comment]
No bo właśnie nie HIGHEST, HIGH ani MONITOR, tylko LOW albo LOWEST. Wtedy zadziała na sto procent.

**Comment by Kenix97** [comment]
Wielkie dzięki! Bardzo ale to bardzo mi pomogłeś! Zamykam!
