### ISSUE TITLE
Nie tworzą sie endercrystale

### ISSUE THREAD

**Issue by MarcinWieczorek** [dzikoysk/FunnyGuilds#333]
Witam. Posiadam najnowszą wersję pluginu, jednak nie tworzą się crystale w bazach, przez co niemożliwe jest podbijanie gildii. Proszę o pomoc, jeśli trzeba wyślę konfigurację itp.

**Comment by TheMolkaPL** [comment]
Podaj wersję silnika serwer i wersję pluginu.

**Comment by MarcinWieczorek** [comment]
O, cześć TheMolkaPL :D
Craftbukkit 1.7.2
FunnyGuilds najnowsze, 3.9.9.1

Tak się zastanawiam czy to może clearlag mi je usuwa

**Comment by artur9010** [comment]
Potwierdzam.

**Comment by MarcinWieczorek** [comment]
Ej, wiecie, że przez ten błąd zacząłem pisać NG? :D
