### ISSUE TITLE
[Propozycja] Wsparcie dla Cauldron'a 

### ISSUE THREAD

**Issue by doktormen1** [dzikoysk/FunnyGuilds#334]
Ponieważ jako cel obrałem silnik "cauldron" bardzo mi zależało też na gildiach a jednak dowiedziałem się że nie ma wsparcia i sam się przekonałem że buguje się tab lista i spami w konsoli Oo

**Comment by Dzikoysk** [comment]
Raczej na pewno nie będzie fg pod cauldrona
