### ISSUE TITLE
Problem z chatem (essentials).

### ISSUE THREAD

**Issue by Szeder32** [dzikoysk/FunnyGuilds#335]
Chcę aby punkty były na kolor &8 a mam na niebiesko tak jak jest na ss'sie: http://scr.hu/5uxw/r54y4
Jest też spacja po punktach przed ostatnim nawiasem. Tak samo jest z tagiem. Chcę aby był na kolor &2 a jest na niebiesko. SS: http://scr.hu/5uxw/lxd1d.

P.S: Mój config. http://pastebin.com/tf64C1Ab

**Comment by Dzikoysk** [comment]
Wygląd tagu ustawiasz w FunnyGuilds

**Comment by Szeder32** [comment]
Ale... Chatu gildyjnego? Czy ogólnego? Jak tak to gdzie?

**Comment by Szeder32** [comment]
Dobra już mam thx <3
