### ISSUE TITLE
[TabLista] Problem

### ISSUE THREAD

**Issue by Bitilol** [dzikoysk/FunnyGuilds#336]
Witajcie nie wiem czemu zrobiłem sobie tab liste i nia moge wejsc na server. Gdy jest wyłączona moge.
Oto screen : http://i.imgur.com/acPGo1q.png
Czego to jest problem ? 
Oto moja tablista:

player-list:
  1: '&7     &6&lSweetCraft&7&l.mygs&5&l&o.co'
  2: ' &7Online: &c{ONLINE}/100'
  3: '  &2&lINFORMACJE:'
  4: ' &7Punkty: &c{POINTS}'
  5: ' &7Smierci: &c{DEATHS}'
  6: ' &7Zabójstwa: &c{KILLS}'
  7: ' &7Gildia: &c{TAG}'
  8: '&8&m---------------'
  9 '  &2&lTOP GRACZ:'
  10: '&7» 1. &6{PTOP-1}'
  11: '  &2&lTOP GILDIA:'
  12: '&7» 1. &6{GTOP-1}'
# Tablista wlaczona

player-list-enable: true

Na konsoli wyświetla sie tylko to :
[11:23:50 INFO]: ziomek1801[/89.228.5.74:60313] logged in with entity id 1839 at ([MAPA] 251.11854620005528, 5.0, -101.09934231157524)
[11:23:50 INFO]: ziomek1801 lost connection: Disconnected
[11:23:50 INFO]: ziomek1801 left the game.

**Comment by TheMolkaPL** [comment]
Nie można ustawiać dłuższych ciągów znaków w komórkach, niż `16` - ograniczenie klienta Minecrafta.

**Comment by Bitilol** [comment]
Działa dziekuje :+1:

**Comment by Bitilol** [comment]
:rabbit:
