### ISSUE TITLE
pytanie

### ISSUE THREAD

**Issue by kiukiu123** [dzikoysk/FunnyGuilds#345]
Witam,Chcę żeby plugin szybciej zapisywał dane w bazie danych.Jest w configu 1 minuta mogę np. 10 sekund?

**Comment by Dzikoysk** [comment]
Niestety nie

**Comment by TheMolkaPL** [comment]
Plugin jest open-source. Możesz edytować kod.

Za czas zapisu odpowiada klasa `Manager` w `net.dzikoysk.funnyguilds.data`.
https://github.com/Dzikoysk/FunnyGuilds/blob/34f002245f0c2bd6ffd472929ac5d5d487065b62/src/net/dzikoysk/funnyguilds/data/Manager.java#L52

```java
}, Settings.getInstance().dataInterval*60*20, Settings.getInstance().dataInterval*60*20);
```

powinno być w tym przypadku

```java
}, Settings.getInstance().dataInterval*60*20, Settings.getInstance().dataInterval*20);
```

Zapis będzie odczytywany w sekundach.
