### ISSUE TITLE
Chat.

### ISSUE THREAD

**Issue by kiukiu123** [dzikoysk/FunnyGuilds#346]
Witam, (Drugi raz :3) co zrobić by na chacie pisało nazwę gildii robię Jak trzeba.I nic.

Dla tych którzy myślą że ciotą jestem.
![wyjasnij](https://cloud.githubusercontent.com/assets/13031588/8331626/a29c6512-1a89-11e5-9f50-113c82eb03d0.jpg)

LUB

http://screenshot.net/dr479tw

**Comment by dzikoysk** [comment]
Dodać {GUILD} :)
