### ISSUE TITLE
Problem FunnyGuilds

### ISSUE THREAD

**Issue by bartek81005** [Dzikoysk/FunnyGuilds#347]
Witam pytanie skierowane do TheMolkaPL
Mogl bys naprawic przy wersji 1.8 ten oto blad : 
[IndependentThread/WARN]:     java.lang.ArrayIndexOutOfBoundsException: 60
[IndependentThread/WARN]:     at net.dzikoysk.funnyguilds.util.element.PlayerList.split(PlayerList.java:34)
[IndependentThread/WARN]:     at net.dzikoysk.funnyguilds.util.element.PlayerList.send(PlayerList.java:97)
[IndependentThread/WARN]:     at net.dzikoysk.funnyguilds.util.thread.Action.execute(Action.java:43)
[IndependentThread/WARN]:     at net.dzikoysk.funnyguilds.util.thread.IndependentThread.execute(IndependentThread.java:39)
[IndependentThread/WARN]:     at net.dzikoysk.funnyguilds.util.thread.IndependentThread.run(IndependentThread.java:27)

**Comment by TheMolkaPL** [comment]
@Thefilippop1PL popsuł bo próbował robić tablistę. xd
Zaraz wprowadzę poprawkę.

**Comment by bartek81005** [comment]
wow dziekuje za tak szybka odpowiedz :D

**Comment by TheMolkaPL** [comment]
Gotowe! @Dzikoysk mógłbyś zamknąć? :)

**Comment by bartek81005** [comment]
A mogl bys dac jara za tepy jestem zeby kompilowac :c

**Comment by TheMolkaPL** [comment]
Właśnie o to chodzi, aby nie każdy te gildie miał. Chodzi o to, aby dzieci ze swoimi pirackimi klientami zostały na 1.7 ;)

**Comment by bartek81005** [comment]
Dalbys jakis kontakt do siebie ?
