### ISSUE TITLE
Konflikt ze skript

### ISSUE THREAD

**Issue by MetaX96** [Dzikoysk/FunnyGuilds#350]
Czy da się jakoś naprawić, aby fg działał poprawnie z pluginem skript?
Problem polega na tym, że nie działa informacja na czacie po zabójstwie/śmierci gracza. Po prostu nie wyświetla się ona. W konsoli,logach nie ma żadnych błędów.

**Comment by TheMolkaPL** [comment]
Któryś z Twoich skryptów lub/i pluginów usuwa wiadomość przy śmierci.

**Comment by MetaX96** [comment]
Problem tkwił w konfiguracji pluginu WorldGuard. Po usunieciu folderu wg, problem znikł.
