### ISSUE TITLE
Zmiana na mysql

### ISSUE THREAD

**Issue by druch5** [Dzikoysk/FunnyGuilds#351]
Witajcie, mam pytanie gdzie jest plik .db który bym mógł wstawić do swojej bazy danych ponieważ chcę zmienić sposób przechowywania danych na mysql?

**Comment by TheMolkaPL** [comment]
Wszystkie dane zapisują się w YAML. Nie ma możliwości skopiowania plików i wklejenia ich do bazy danych.

Nie jestem pewien, ale jest komenda na transfer danych z pliku do bazy poprzez odczyt i zapis danych.
