### ISSUE TITLE
FunnyGuilds Biblioteki

### ISSUE THREAD

**Issue by Inder00** [Dzikoysk/FunnyGuilds#354]
Mam pytanie, jakich bibliotek aktualnie posiadasz w projekcie ?
np.
Bukkit 1.4.2 R0.1

proszę o odpowiedź bo mam problem u siebie w pluginie od bubliotek

**Comment by TheMolkaPL** [comment]
Jest to tylko i wyłącznie `Spigot 1.7` dla `3.9.9.1` (lub `Spigot 1.8` dla wersji `pre 4.0`).

Posiada on w sobie także Netty oraz Google Guava. Gotowy plik POM, jeżeli używasz Apache Maven [znajdujesz u mnie](https://github.com/TheMolkaPL/FunnyGuilds/blob/mc1.8/pom.xml).
