### ISSUE TITLE
Blad z Rankingiem

### ISSUE THREAD

**Issue by Lasot** [dzikoysk/FunnyGuilds#358]
Plugin dziala pieknie poza rankingiem na tabliscie poniewaz pokazuje np przy 980 = 9800 nie rozumiem o co chodzi.
Wersja 1.7.10

**Comment by TheMolkaPL** [comment]
Można prosić o Twoją konfigurację? Wklej ją na [Pastebin](http://pastebin.com).

**Comment by Lasot** [comment]
Prosze oto config, dodam tez ze przy zmianie pozycji cos jest nie tak z nazwami graczy w topce dostaja jakies dodatkowe znaki.
http://pastebin.com/2DgBMaak
