### ISSUE TITLE
Baza.

### ISSUE THREAD

**Issue by Artey842** [dzikoysk/FunnyGuilds#362]
Pomoże mi ktoś połączyć się z Bazą? 

IP/Host:	db2.slotex.pl
Port:	3306 (domyślny)
Użytkownik:	game_56815
Hasło:	nuNL4N7XgD9F0B6C
Nazwa bazy:	game_56815

**Comment by TheMolkaPL** [comment]
To jest bug tracker pluginu FunnyGuilds, nie wsparcie techniczne.
