### ISSUE TITLE
Usuwanie gildii w najnowszej wersji pluginu

### ISSUE THREAD

**Issue by oskar99989** [dzikoysk/FunnyGuilds#365]
Jak usunąć graczowi gildię lub ustawić ranking w najnowszej wersji pluginu? Ponieważ /ga już nie działa.

**Comment by TheMolkaPL** [comment]
Dlaczego nie działa?

https://github.com/dzikoysk/FunnyGuilds/blob/3.9.9.1/src/net/dzikoysk/funnyguilds/FunnyGuilds.java#L62

https://github.com/dzikoysk/FunnyGuilds/blob/f0d9297d41d7a76efbd3a2a61c7646cd10a2ccb8/src/main/java/net/dzikoysk/funnyguilds/command/Commands.java#L41

https://github.com/dzikoysk/FunnyGuilds/blob/3.9.9.1/src/net/dzikoysk/funnyguilds/command/admin/AxcDelete.java

**Comment by oskar99989** [comment]
Pisze, że nie ma takiej komendy gdy wpisuję /ga.

**Comment by TheMolkaPL** [comment]
Pokaż logi z włączania serwera. Musiał tam wystąpić jakiś błąd.
