### ISSUE TITLE
PROBLEM NIE ZNALEZIONO KOMEND

### ISSUE THREAD

**Issue by MedoodeM** [dzikoysk/FunnyGuilds#366]
Witam mam problem z owym pluginem, kiedy wpisuje /pl wyswietla sie, ze wszystko dziala lecz jak wpisze byle jaka komende zwiazana z pluginem, np. /g, /ga, /zaloz, /dolacz to na chacie wyswietla sie jakby ta komenda nie istniala, prosze o pomoc

**Comment by TheMolkaPL** [comment]
Proszę podać log z włączania serwera - tam musiał wystąpić błąd przy włączaniu pluginu.

**Comment by MedoodeM** [comment]
Po kilkukrotnym reinstallu udalo mi sie naprawic :)
