### ISSUE TITLE
Nie Dziala Tab Lista! Pomocy!

### ISSUE THREAD

**Issue by ejer246** [dzikoysk/FunnyGuilds#368]
Mój Config:

`player-list:
1: ''
2: ''
3: ' &9&lProGame'
4: ' &7Online: &c{ONLINE}/1000'
5: ' &2&lINFORMACJE:'
6: ' &7Punkty: &c{POINTS}'
7: ' &7Smierci: &c{DEATHS}'
8: ' &7Zabójstwa: &c{KILLS}'
9: ' &7Gildia: &c{TAG}'
10: '&8&m----------------'
11: ' &2&lTOP 3 GRACZY:'
12: ' &7» 1. &6{PTOP-1}'
13: ' &7» 2. &6{PTOP-2}'
14: ' &7» 3. &6{PTOP-3}'
15: ' &2&lTOP 3 GILDIE:'
16: ' &7» 1. &6{GTOP-1}'
17: ' &7» 2. &6{GTOP-2}'
18: ' &7» 3. &6{GTOP-3}'
19: ''
20: ''
# Tablista wlaczona

player-list-enable: true
# Co ile sekund ma odswiezac liste graczy

player-list-interval: 1
# Ping wyswietlany na tab

player-list-ping: 9999
# Jezeli buguje Ci sie tablista
# \- Po wejsciu gracza wszystko sie rozjezdza
# Wlacz ta opcje

player-list-patch: false
# Wyglad punktow wyswietlanych przy gildii w rankingu

player-list-points: '&8[&8{POINTS}&8]'
`
Mam Ustawione 20 Slotów.
Tab Listy Nie Widać.
SRCEEN:
[http://i.imgur.com/KdO4nii.png](url)

**Comment by TheMolkaPL** [comment]
^^

![image](https://cloud.githubusercontent.com/assets/4578571/18006952/4f5b8eda-6ba2-11e6-91be-97e6e34f70b8.png)

Podaj logi z włączania pluginu podczas włączania serwera.

**Comment by ejer246** [comment]
To trudne bo mam masę skryptów i innych i przy wlaczaniu nie widze żadnej wiadomości bo jest ich pełno xd.

**Comment by TheMolkaPL** [comment]
Spokojnie, znajdziemy. Włączanie serwera jest "posegregowane".
