### ISSUE TITLE
Nie pokazuje wiadomości za zabicie

### ISSUE THREAD

**Issue by ejer246** [dzikoysk/FunnyGuilds#369]
Gdy jakiś gracz zabije innego to na chatcie nie wyświetla się powiadomienie o zbiciu i punktach.
Ten problem mam dopiero od jakiegoś czasu. Wcześniej wszystko działało jak należy ale ostatnio nie działa. ;-;. pomocy. ;-;

**Comment by artur9010** [comment]
Gratulacje! Jesteś 100 osobą która zgłosiła buga do martwego projektu, w nagrodę nie dostaniesz nic :cactus:

**Comment by Daffiteq** [comment]
Gratulacje, zainstalowałeś HideStream!

A teraz wyłącz ukrywanie wiadomości śmierci w konfiguracji lub odinstaluj wyżej wymieniony plugin.

Pozdrawiam, Daffitoysk!
