### ISSUE TITLE
Jaki silnik (API)

### ISSUE THREAD

**Issue by rekkin** [dzikoysk/FunnyGuilds#370]
Witam, jaki jest silnik zastosowany do source code fg? Fajnie gdyby ktoś podesłał link do silnika. Jeśli ktoś nie rozumie to potrzebuje API do source code który wrzucę np do eclipse.

**Comment by dzikoysk** [comment]
Nie ogarniam o co pytasz, więc wypisuję rzeczy na zasadzie skojarzeń, może to właśnie o któreś pytasz:
* IDE: IntelliJ IDEA
* Source 3.9.9.1 pobierzesz tutaj: https://github.com/dzikoysk/FunnyGuilds/releases
* Kod z repo nie działa, bo nie jest skończony, dlatego pewnie wolisz bazować na wyżej wymienionym 3.9.9.1

**Comment by rekkin** [comment]
Można wiedzieć jaki dokładny build tego bukkita 1.7.2? Gdy wrzucam silniki pod ten source code to wywala mi pare błędów ;/.

**Comment by dzikoysk** [comment]
Pewnie najnowszy stabilny, czyli jakieś R2, albo R3 jak było. Aczkolwiek na żadnym nie powinno Ci wywalać błędów. Upewnij się, że nie masz obecnej wersji z githuba.

**Comment by rekkin** [comment]
Nie brać najnowszych FunnyGuildsów (3.9.9.1)? Która wersja funnyguilds open source jest najbardziej stabilna?

**Comment by dzikoysk** [comment]
3.9.9.1 była w miarę stabilna: https://github.com/dzikoysk/FunnyGuilds/archive/3.9.9.1.zip
Miałem na myśli tylko to, abyś upewnił się, że pobierasz z tego linku, a nie z obecnego repo, bo tam leży niedokończona wersja 4.0

**Comment by rekkin** [comment]
okej, dzięki wielkie :)

**Comment by rekkin** [comment]
btw. bukkit-1.7.2-R0.4-20140216.011848-2.jar z https://tcpr.ca/downloads/bukkit będzie git?

**Comment by dzikoysk** [comment]
Powinien być ok 👌

**Comment by rekkin** [comment]
Wywala mi trochę błędów z importami :(

import net.minecraft.util.com.google.common.base.Charsets;
import net.minecraft.util.com.google.common.io.Files;

.getProfile() (error The method getProfile() from the type OfflineUser refers to the missing type GameProfile) 

i trochę więcej ;/.

Chyba ten silnik nie jest dobry xD

**Comment by dzikoysk** [comment]
Faktycznie, moja wina. Zapomniałem, że używane tam są importy bezpośrednio z craftbukkita. Poszukaj cb na 1.7.2 i wrzuć go zamiast bukkita.

**Comment by rekkin** [comment]
W eclipse mi wszystko działa ładnie, ale wywala błędy w mc :(.

Silnik This server is running CraftBukkit version git-PaperSpigot-1f7d532 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)

Błedy w konsolce http://pastebin.com/eBXDhCck

**Comment by dzikoysk** [comment]
No tu się musisz sam bawić, ja poprawianiem fg się już nie zajmuję

**Comment by SlimaKCoder** [comment]
@dzikoysk właściwie czemu porzuciłeś ten projekt? W sumie nie ma żadnej konkurencji praktycznie, a już jest tak znany, że mółby się wybić spokojnie

**Comment by rekkin** [comment]
@dzikoysk wgl. przynajmniej powiedz jak naprawić te błędy xD

**Comment by dzikoysk** [comment]
@SlimaKCoder ciekawsze projekty, bo pisanie gildii to po prostu nudne zajęcie. Teraz też żeby coś ciekawego z tym zrobić, to wszystko by trzeba na spokojnie na nowo napisać, bo kontynuowanie nie ma sensu. Dużo roboty, a zysku jak nie było tak nie będzie. Zresztą ogólnie mam wrażenie, że community trochę przymarło ostatnio.

@rekkin tu by warto się do podstaw odwołać, bo bez nich i tak nic nie zrobisz
```javascript
java.lang.NullPointerException
    at net.dzikoysk.funnyguilds.data.Settings.load(Settings.java:209) ~[?:?]
```

**Comment by rekkin** [comment]
A ile byś oczekiwał za taki plugin na gildie w podobie do FG? Tylko szczerze xd

**Comment by SlimaKCoder** [comment]
@dzikoysk Zysk by był, ale byś musiał to umieć sprzedać. Czemu nie zrobisz na zasadzie, że plugin z githuba jest za darmo, ale jak ktoś chce wsparcie (np. ogarnianie jego issues, instalacja na jego serwerze, etc) to musi wykupić subskrypcję miesięczną (może być nawet przez SMS). Może nie będzie hord ludzi, ale na pewno sporo osób by się skusiło.

**Comment by dzikoysk** [comment]
Pomysł dosyć stary, nawet nie wiem czy nawet tu gdzieś nie było już przy pierwszych wersjach, żeby przejść na model subskrypcji. Tylko zakładał taki model jako jedyny (bez wersji free). Może i miałoby to sens, gdyby było teraz na to wzięcie.

**Comment by rekkin** [comment]
ja bym brał xDD

**Comment by dzikoysk** [comment]
To zbierz jeszcze co najmniej 100 osób ( ͡° ͜ʖ ͡°)

**Comment by rekkin** [comment]
Wrzucisz temat na mpc to na pewno zbierzesz dużo osób ;d.

**Comment by artur9010** [comment]
Jak za darmo to i ja wezme :lenny:
