### ISSUE TITLE
Jakiś error z Panda

### ISSUE THREAD

**Issue by rekkin** [dzikoysk/FunnyGuilds#371]
Elo, o co chodzi? http://hastebin.com/yapakoraxa.vbs

**Comment by dzikoysk** [comment]
Robiłeś może reload?

**Comment by rekkin** [comment]
Tak

**Comment by rekkin** [comment]
tak, caly czas wywala blad, przy starcie serwera i po reload ;/

**Comment by dzikoysk** [comment]
Hmmm... jesteś w stanie spróbować na wersji 1.7.2? 

Generalnie wszystko się ładnie zbuildowało, więc dziwi mnie, że tego nie znajduje. Zresztą gdyby coś było nie tak, to też by mi sypnęło 
![Cons](https://panda-lang.org/screenshot/MPSIpyVl.png)

**Comment by rekkin** [comment]
Jest jakiś inny kontakt do Ciebie niż github? Słaba jest tu komunikacja ;D

**Comment by dzikoysk** [comment]
Może discord fg? :) 

https://discord.gg/86Wf5QE

**Comment by rekkin** [comment]
nie ;/

**Comment by dzikoysk** [comment]
Skype?

**Comment by rekkin** [comment]
Napisałem do Ciebie :)

**Comment by wvffle** [comment]
A ja jestem za tym, by bylo to rozwiazane na githubie. Ktos jeszcze bedzie mial ten sam problem, to bedzie mozna sie odwolac.

**Comment by SlimaKCoder** [comment]
@wvffle dokładnie, bo po tytule "Jakiś error" będzie potem łatwo wyszukać ;D

**Comment by wvffle** [comment]
dlatego dzik powinien ustalic jakies ramy

**Comment by wvffle** [comment]
a @rekkin zmienic tytul na bardziej konkretny i napisac wiecej o bledzie

**Comment by dzikoysk** [comment]
@rekkin nie dostałem wiadomości :<

Wyszło 3.9.9.3, sprawdź ją może

**Comment by rekkin** [comment]
na skype masz taki sam avatar jak na git?

**Comment by dzikoysk** [comment]
Tak
