### ISSUE TITLE
Mam problem z Pandą

### ISSUE THREAD

**Issue by SlimaKCoder** [dzikoysk/FunnyGuilds#373]
http://www.seerinteractive.com/wp-content/uploads/2015/03/Seer-Blog-Google-Panda-Algorithm-1440x700.jpg
![image](https://cloud.githubusercontent.com/assets/4578571/20967813/7618e434-bc81-11e6-8809-425acc6a6304.png)

Fochła się, bo twierdzi, że źle ją karmię.... zwykle daje jej bambusy, ale co ona może innego jeść? Pomóżcie!

**Comment by MrGregorix** [comment]
Dorosłe pandy żywią się głównie bambusem, pąkami kwiatów, żołędziami i duszami swoich wrogów.

**Comment by kamcio96** [comment]
Spróbuj tego rozwiązania: https://www.youtube.com/watch?v=z6t0KC2Bf3w

**Comment by MrGregorix** [comment]
Nie bije się pand :(

**Comment by kamcio96** [comment]
To była tylko obrona psa :<

**Comment by artur9010** [comment]
Może ma raka?

**Comment by wvffle** [comment]
Pandy nie maja raka! Maja male pandki!

**Comment by artur9010** [comment]
To w sumie prawie jak rak...

**Comment by MrGregorix** [comment]
nowotwór*

**Comment by artur9010** [comment]
Rak, bo pandy są złośliwe.

**Comment by SlimaKCoder** [comment]
Mój problem z pandą nie został rozwiązany... nadal ma focha. Może jedzenie to za mało, co takie pandy lubią robić? Myślałem zabrać ją na wycieczkę do zoo.... no ale sami wiecie ;/

**Comment by artur9010** [comment]
@SlimaKCoder żeby zobaczyła jak dobrze żyją inne pandy? To nie dość, że będzie miała focha to będzie zazdrosna...
